import React, { useState } from "react";
import { Link } from "react-router-dom";
import { getRandomJobId } from "../services/quizService"; // ✅ use service method

const Home = () => {
    const [demoLoading, setDemoLoading] = useState(false);

    const handleTryDemo = async () => {
        if (demoLoading) return;
        setDemoLoading(true);
        try {
            const jobId = await getRandomJobId();
            const frontendOrigin =
                typeof window !== "undefined" ? window.location.origin : "";
            window.location.href = `${frontendOrigin}/quiz_generate?job_id=${encodeURIComponent(
                jobId
            )}`;
        } catch (e) {
            console.error(e);
            alert(e?.message || "Could not start demo quiz.");
            setDemoLoading(false);
        }
    };

    return (
        <main className="bg-white" style={{ color: "var(--cqu-text)", fontFamily: "var(--cqu-font)" }}>
            {/* HERO — deep CQU color */}
            <section
                className="py-20 md:py-28"
                style={{ backgroundColor: "var(--cqu-text)", color: "white" }}
            >
                <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 text-center">
                    <h1 className="text-4xl md:text-5xl font-bold tracking-tight mb-4">
                        QuizGPT — Quizzes from Your Study Materials
                    </h1>
                    <p className="mx-auto max-w-3xl text-lg md:text-xl leading-relaxed opacity-95">
                        Upload notes, PDFs, or textbook chapters. QuizGPT instantly creates fresh quizzes with hints
                        and explanations. Progress unlocks section-by-section to ensure true understanding.
                    </p>

                    <div className="mt-8 flex flex-wrap items-center justify-center gap-4">
                        <Link
                            to="/login"
                            className="px-6 py-3 rounded-lg font-semibold shadow-sm transition-transform active:scale-[0.98]"
                            style={{ backgroundColor: "var(--cqu-accent)", color: "var(--cqu-text)" }}
                        >
                            Upload Material & Generate Quiz
                        </Link>

                        {/* Try a Demo via quizService */}
                        <button
                            onClick={handleTryDemo}
                            disabled={demoLoading}
                            className="px-6 py-3 rounded-lg font-semibold shadow-sm transition-transform active:scale-[0.98] disabled:opacity-60"
                            style={{ backgroundColor: "white", color: "var(--cqu-text)" }}
                        >
                            {demoLoading ? "Starting demo…" : "Try a Demo Quiz"}
                        </button>
                    </div>

                    <div className="mt-6 text-sm opacity-90">
                        No fixed banks • New questions every run • Quiz are generated by AI
                    </div>
                </div>
            </section>

            {/* WHY (3-up cards) — light bg, no border/shadow */}
            <section className="py-16 px-4 sm:px-6 lg:px-8">
                <h2 className="text-2xl md:text-3xl font-bold text-center">Why QuizGPT?</h2>
                <div className="mx-auto mt-10 grid max-w-6xl gap-8 md:grid-cols-3 text-center">
                    <div className="p-6 rounded-2xl" style={{ backgroundColor: "var(--cqu-card)" }}>
                        <div className="text-4xl mb-2">📄➡️❓</div>
                        <h3 className="text-xl font-semibold mb-2">Instant Quiz Generation</h3>
                        <p className="opacity-90">
                            Turn any document into MCQs, true/false, and short answers in seconds.
                        </p>
                    </div>
                    <div className="p-6 rounded-2xl" style={{ backgroundColor: "var(--cqu-card)" }}>
                        <div className="text-4xl mb-2">💡</div>
                        <h3 className="text-xl font-semibold mb-2">Hints & Explanations</h3>
                        <p className="opacity-90">
                            Each question includes helpful hints and clear rationales to build understanding.
                        </p>
                    </div>
                    <div className="p-6 rounded-2xl" style={{ backgroundColor: "var(--cqu-card)" }}>
                        <div className="text-4xl mb-2">🔒➡️🔓</div>
                        <h3 className="text-xl font-semibold mb-2">Progress-Locked Flow</h3>
                        <p className="opacity-90">
                            Finish one section cleanly to unlock the next—steady, confident progress.
                        </p>
                    </div>
                </div>
            </section>

            {/* FEATURES — light cards, no borders/shadows */}
            <section className="py-16" style={{ backgroundColor: "#F7FAF9" }}>
                <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
                    <h2 className="text-2xl md:text-3xl font-bold text-center">Features</h2>
                    <p className="mx-auto mt-3 max-w-2xl text-center opacity-80">
                        Built for classrooms and self-study. Fresh, adaptive questions keep learners engaged.
                    </p>

                    <div className="mt-12 grid gap-8 md:grid-cols-2 lg:grid-cols-3">
                        {[
                            ["🎯", "Adaptive Difficulty", "Question difficulty adjusts to performance automatically."],
                            ["🗂️", "Section-Aware Quizzing", "Upload by chapters; quizzes follow your content structure."],
                            ["👩‍🏫", "Teacher Mode", "Upload course content, review completion."],
                            ["🧩", "Mixed Question Types", "MCQ, true/false, short answers with hints and rationales."],
                            ["📈", "Progress & Scores", "Track per-section mastery and quiz history."],
                            ["⬇️", "Export/Share", "Download items or share a test link quickly."],
                        ].map(([icon, title, text]) => (
                            <div key={title} className="p-6 rounded-xl" style={{ backgroundColor: "var(--cqu-card)" }}>
                                <div className="text-2xl mb-2">{icon}</div>
                                <h3 className="font-semibold text-lg mb-1">{title}</h3>
                                <p className="opacity-90">{text}</p>
                            </div>
                        ))}
                    </div>
                </div>
            </section>

            {/* HOW IT WORKS */}
            <section className="py-16 px-4 sm:px-6 lg:px-8">
                <h2 className="text-2xl md:text-3xl font-bold text-center">How It Works</h2>
                <div className="mx-auto mt-10 max-w-3xl">
                    <ol className="space-y-5 text-lg">
                        <li><span className="font-semibold">1. Upload</span> notes, slides, or chapters (PDF, DOCX, text).</li>
                        <li><span className="font-semibold">2. Generate</span> a fresh quiz with hints and explanations—instantly.</li>
                        <li><span className="font-semibold">3. Attempt</span> the quiz. Incorrect answers show targeted hints.</li>
                        <li><span className="font-semibold">4. Unlock</span> the next section after a clean pass—repeat and master.</li>
                    </ol>
                </div>
            </section>

            {/* PATHS: STUDENTS / TEACHERS — light cards, no borders/shadows */}
            <section className="py-16" style={{ backgroundColor: "#F7FAF9" }}>
                <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 grid gap-8 md:grid-cols-2">
                    <div className="p-8 rounded-2xl" style={{ backgroundColor: "var(--cqu-card)" }}>
                        <h3 className="text-xl font-bold mb-2">For Students</h3>
                        <p className="opacity-90">
                            Visit the link provided on the moodle site, and practice quizzes for this week's topics.
                        </p>
                    </div>

                    <div className="p-8 rounded-2xl" style={{ backgroundColor: "var(--cqu-card)" }}>
                        <h3 className="text-xl font-bold mb-2">For Tutors</h3>
                        <p className="opacity-90">
                            Please sign up and upload course weekly materials to generate quizzes for your students.
                        </p>
                        <Link
                            to="/login"
                            className="inline-block mt-5 px-5 py-2.5 rounded-lg font-semibold"
                            style={{ backgroundColor: "white", color: "var(--cqu-text)" }}
                        >
                            Sign In
                        </Link>
                    </div>
                </div>
            </section>
        </main>
    );
};

export default Home;
